// AUTO-GENERATED by scripts/generate_pairs.mjs — do not hand-edit.
// Regenerate: node scripts/link_wireframe_controls.mjs && node scripts/generate_pairs.mjs
// Section-level PAIRS follow the S1(b) rule: one entry per .grp[data-fxsec],
// else whole panel → .fx-ctrl[data-fxsec=<key>]. Alias: wireframe masks → app local.
// Labels are hand-written (LABELS map in the generator), preserved across regeneration.

export const SECTION_PAIRS = {
  ".topbar": {
    "app": "#fx-deskbar",
    "label": "topbar",
    "zone": "topbar"
  },
  ".tb-left .undogrp": {
    "app": ".fx-undogrp",
    "label": "undo/redo cluster",
    "zone": "topbar"
  },
  ".zoomctl": {
    "app": "#fx-zoom-ctrl",
    "label": "zoom control",
    "zone": "zoom"
  },
  "#btn-tools": {
    "app": "#fx-settings .fx-db",
    "label": "Settings button (was Tools)",
    "zone": "topbar"
  },
  "#btn-allfx": {
    "app": ".js-allfx",
    "label": "All FX button",
    "zone": "topbar"
  },
  ".btn-export": {
    "app": "#btn-fx-export, [onclick*=\"exportFX\"]",
    "label": "Export button",
    "zone": "topbar"
  },
  ".rail": {
    "app": "#fx-toolrail",
    "label": "tool rail",
    "zone": "rail"
  },
  ".toolpanel": {
    "app": ".fx-panel",
    "label": "tool panel",
    "zone": "panel"
  },
  ".filmstrip": {
    "app": "#lib-overlay:not(.full)",
    "label": "filmstrip (docked library)",
    "zone": "filmstrip"
  },
  ".statusbar": {
    "app": "#fx-statusbar",
    "label": "status bar",
    "zone": "statusbar"
  },
  ".tp-panel[data-panel=\"looks\"]": {
    "app": ".fx-ctrl[data-fxsec=\"looks\"]",
    "label": "looks panel",
    "zone": "looks-panel"
  },
  ".tp-panel[data-panel=\"adjust\"]": {
    "app": ".fx-ctrl[data-fxsec=\"adjust\"]",
    "label": "adjust panel",
    "zone": "adjust-panel"
  },
  ".tp-panel[data-panel=\"crop\"] .grp[data-fxsec=\"crop\"]": {
    "app": ".fx-ctrl[data-fxsec=\"crop\"]",
    "label": "crop panel",
    "zone": "crop-panel"
  },
  ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"]": {
    "app": ".fx-ctrl[data-fxsec=\"nr\"]",
    "label": "noise reduction section",
    "zone": "detail-panel"
  },
  ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"]": {
    "app": ".fx-ctrl[data-fxsec=\"lens\"]",
    "label": "lens correction section",
    "zone": "detail-panel"
  },
  ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"deconv\"]": {
    "app": ".fx-ctrl[data-fxsec=\"deconv\"]",
    "label": "deconvolution section",
    "zone": "detail-panel"
  },
  ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"curves\"]": {
    "app": ".fx-ctrl[data-fxsec=\"curves\"]",
    "label": "tone curves section",
    "zone": "color-panel"
  },
  ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"hsl\"]": {
    "app": ".fx-ctrl[data-fxsec=\"hsl\"]",
    "label": "color mixer section",
    "zone": "color-panel"
  },
  ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"]": {
    "app": ".fx-ctrl[data-fxsec=\"pointcolor\"]",
    "label": "point color section",
    "zone": "color-panel"
  },
  ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"wheels\"]": {
    "app": ".fx-ctrl[data-fxsec=\"wheels\"]",
    "label": "colour wheels section",
    "zone": "color-panel"
  },
  ".tp-panel[data-panel=\"retouch\"]": {
    "app": ".fx-ctrl[data-fxsec=\"retouch\"]",
    "label": "retouch panel",
    "zone": "retouch-panel"
  },
  ".tp-panel[data-panel=\"masks\"]": {
    "app": ".fx-ctrl[data-fxsec=\"local\"]",
    "label": "masks panel",
    "zone": "masks-panel"
  },
  ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"]": {
    "app": ".fx-ctrl[data-fxsec=\"grain\"]",
    "label": "film grain section",
    "zone": "film-panel"
  },
  ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"]": {
    "app": ".fx-ctrl[data-fxsec=\"hal\"]",
    "label": "halation section",
    "zone": "film-panel"
  },
  ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"bloom\"]": {
    "app": ".fx-ctrl[data-fxsec=\"bloom\"]",
    "label": "bloom section",
    "zone": "film-panel"
  },
  ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"art\"]": {
    "app": ".fx-ctrl[data-fxsec=\"art\"]",
    "label": "film artifacts section",
    "zone": "film-panel"
  },
  ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"vig\"]": {
    "app": ".fx-ctrl[data-fxsec=\"vig\"]",
    "label": "vignette section",
    "zone": "film-panel"
  },
  ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"]": {
    "app": ".fx-ctrl[data-fxsec=\"borders\"]",
    "label": "border section",
    "zone": "frame-panel"
  },
  ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"canvas\"]": {
    "app": ".fx-ctrl[data-fxsec=\"canvas\"]",
    "label": "canvas section",
    "zone": "frame-panel"
  },
  ".tp-panel[data-panel=\"export\"]": {
    "app": ".fx-ctrl[data-fxsec=\"export\"]",
    "label": "export panel",
    "zone": "export-panel"
  },
  ".tp-panel[data-panel=\"info\"]": {
    "app": ".fx-ctrl[data-fxsec=\"info\"]",
    "label": "info panel",
    "zone": "info-panel"
  }
};

export const CONTROL_PAIRS = [
  {
    "wf": ".tp-panel[data-panel=\"looks\"] button.select-btn",
    "app": "#sel-input",
    "label": "sRGB",
    "panel": "looks",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"looks\"] input",
    "app": "#sl-lut-mix",
    "label": "Strength",
    "panel": "looks",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"adjust\"] input",
    "app": "#sl-adj-exp",
    "label": "Exposure",
    "panel": "adjust",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"adjust\"] input",
    "app": "#sl-adj-con",
    "label": "Contrast",
    "panel": "adjust",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"adjust\"] input",
    "app": "#sl-adj-hi",
    "label": "Highlights",
    "panel": "adjust",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"adjust\"] input",
    "app": "#sl-adj-sh",
    "label": "Shadows",
    "panel": "adjust",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"adjust\"] input",
    "app": "#sl-adj-wh",
    "label": "Whites",
    "panel": "adjust",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"adjust\"] input",
    "app": "#sl-adj-bl",
    "label": "Blacks",
    "panel": "adjust",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"crop\"] .grp[data-fxsec=\"crop\"] input",
    "app": "#sl-straighten",
    "label": "Straighten",
    "panel": "crop",
    "fxsec": "crop"
  },
  {
    "wf": ".tp-panel[data-panel=\"crop\"] .grp[data-fxsec=\"crop\"] button.wide-btn.ghost",
    "app": "#btn-ah-roi",
    "label": "Aspect",
    "panel": "crop",
    "fxsec": "crop"
  },
  {
    "wf": ".tp-panel[data-panel=\"crop\"] .grp[data-fxsec=\"crop\"] button.select-btn",
    "app": "#sel-crop-grid",
    "label": "Grid",
    "panel": "crop",
    "fxsec": "crop"
  },
  {
    "wf": ".tp-panel[data-panel=\"crop\"] .grp[data-fxsec=\"crop\"] button.wide-btn.primary",
    "app": "#btn-crop",
    "label": "Aspect",
    "panel": "crop",
    "fxsec": "crop"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] div.seg",
    "app": "#sel-raw-nr",
    "label": "",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] input",
    "app": "#sl-nr-high-strength",
    "label": "High strength i",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] button.wide-btn.ghost",
    "app": "#btn-denoise-cancel",
    "label": "",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] input",
    "app": "#sl-nr-lum",
    "label": "Luminance",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] input",
    "app": "#sl-nr-col",
    "label": "Color",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] input",
    "app": "#sl-nr-det",
    "label": "Detail",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] input",
    "app": "#sl-adj-sharp",
    "label": "Sharpen",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"] input",
    "app": "#sl-nr-hldesat",
    "label": "Highlight desaturation i",
    "panel": "detail",
    "fxsec": "nr"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-dist",
    "label": "Distortion",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-vig",
    "label": "Vignette",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-ca",
    "label": "Chromatic aberration",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-pv",
    "label": "Vertical",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-ph",
    "label": "Horizontal",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-rot",
    "label": "Rotate",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-scale",
    "label": "Scale",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input",
    "app": "#sl-lens-defr",
    "label": "Defringe",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"] input.txt",
    "app": "#in-lens-manual-focal",
    "label": "Focal length (mm)",
    "panel": "detail",
    "fxsec": "lens"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"deconv\"] input",
    "app": "#sl-deconv-amt",
    "label": "Amount",
    "panel": "detail",
    "fxsec": "deconv"
  },
  {
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"deconv\"] input",
    "app": "#sl-deconv-rad",
    "label": "Radius",
    "panel": "detail",
    "fxsec": "deconv"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"curves\"] button.sw",
    "app": "#tg-curves",
    "label": "Tone curve",
    "panel": "color",
    "fxsec": "curves"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"hsl\"] button.sw",
    "app": "#tg-hsl",
    "label": "Color mixer",
    "panel": "color",
    "fxsec": "hsl"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"hsl\"] input",
    "app": "#sl-hsl-h",
    "label": "Hue",
    "panel": "color",
    "fxsec": "hsl"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"hsl\"] input",
    "app": "#sl-hsl-s",
    "label": "Saturation",
    "panel": "color",
    "fxsec": "hsl"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"hsl\"] input",
    "app": "#sl-hsl-l",
    "label": "Luminance",
    "panel": "color",
    "fxsec": "hsl"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"] button.sw",
    "app": "#tg-pointcolor",
    "label": "Point color",
    "panel": "color",
    "fxsec": "pointcolor"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"] input",
    "app": "#sl-pc-h",
    "label": "Hue",
    "panel": "color",
    "fxsec": "pointcolor"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"] input",
    "app": "#sl-pc-s",
    "label": "Saturation",
    "panel": "color",
    "fxsec": "pointcolor"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"] input",
    "app": "#sl-pc-l",
    "label": "Luminance",
    "panel": "color",
    "fxsec": "pointcolor"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"] input",
    "app": "#sl-pc-r",
    "label": "Range",
    "panel": "color",
    "fxsec": "pointcolor"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"wheels\"] button.sw",
    "app": "#tg-wheels",
    "label": "Colour wheels",
    "panel": "color",
    "fxsec": "wheels"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"wheels\"] input",
    "app": "#sl-wheel-lift-l",
    "label": "Shadow brightness",
    "panel": "color",
    "fxsec": "wheels"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"wheels\"] input",
    "app": "#sl-wheel-gamma-l",
    "label": "Midtone brightness",
    "panel": "color",
    "fxsec": "wheels"
  },
  {
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"wheels\"] input",
    "app": "#sl-wheel-gain-l",
    "label": "Highlight brightness",
    "panel": "color",
    "fxsec": "wheels"
  },
  {
    "wf": ".tp-panel[data-panel=\"retouch\"] button.sw",
    "app": "#tg-retouch",
    "label": "Retouch",
    "panel": "retouch",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"retouch\"] div.seg",
    "app": "#sel-heal-mode",
    "label": "",
    "panel": "retouch",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"retouch\"] input",
    "app": "#sl-heal-size",
    "label": "Size",
    "panel": "retouch",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"retouch\"] input",
    "app": "#sl-heal-feather",
    "label": "Feather",
    "panel": "retouch",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"retouch\"] input",
    "app": "#sl-heal-opacity",
    "label": "Opacity",
    "panel": "retouch",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"retouch\"] button.wide-btn.primary",
    "app": "#btn-heal-paint",
    "label": "Mode i",
    "panel": "retouch",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"masks\"] input",
    "app": "#sl-msk-selview-opacity",
    "label": "Overlay opacity",
    "panel": "masks",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"masks\"] button.sw",
    "app": "#tg-msk-edge",
    "label": "Edge only",
    "panel": "masks",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] button.sw",
    "app": "#tg-grain",
    "label": "Film grain",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] input",
    "app": "#sl-grain-a",
    "label": "Amount",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] button.select-btn",
    "app": "#sel-grain-fmt",
    "label": "Film format",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] input",
    "app": "#sl-grain-sz",
    "label": "Size",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] input",
    "app": "#sl-grain-motion",
    "label": "Grain motion",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] input",
    "app": "#sl-gate-weave",
    "label": "Gate weave",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"] input",
    "app": "#sl-film-breath",
    "label": "Film breath",
    "panel": "film",
    "fxsec": "grain"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] button.sw",
    "app": "#tg-hal",
    "label": "Halation",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] input",
    "app": "#sl-hal-a",
    "label": "Amount",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] input",
    "app": "#sl-hal-r",
    "label": "Radius",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] input",
    "app": "#sl-hal-p",
    "label": "Shadow protect i",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] button.sw",
    "app": "#tg-hal-white",
    "label": "White glow",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] button.sw",
    "app": "#tg-hal-noremjet",
    "label": "No remjet",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"] button.sw",
    "app": "#tg-hal-extreme",
    "label": "Extreme",
    "panel": "film",
    "fxsec": "hal"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"bloom\"] button.sw",
    "app": "#tg-bloom",
    "label": "Bloom",
    "panel": "film",
    "fxsec": "bloom"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"bloom\"] input",
    "app": "#sl-bloom-a",
    "label": "Amount",
    "panel": "film",
    "fxsec": "bloom"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"bloom\"] input",
    "app": "#sl-bloom-th",
    "label": "Threshold",
    "panel": "film",
    "fxsec": "bloom"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"bloom\"] input",
    "app": "#sl-bloom-r",
    "label": "Radius",
    "panel": "film",
    "fxsec": "bloom"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"art\"] button.sw",
    "app": "#tg-art",
    "label": "Film artifacts",
    "panel": "film",
    "fxsec": "art"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"art\"] input",
    "app": "#sl-art-du",
    "label": "Dust",
    "panel": "film",
    "fxsec": "art"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"art\"] input",
    "app": "#sl-art-sc",
    "label": "Scratches",
    "panel": "film",
    "fxsec": "art"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"art\"] input",
    "app": "#sl-art-lk",
    "label": "Light leak",
    "panel": "film",
    "fxsec": "art"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"vig\"] button.sw",
    "app": "#tg-vig",
    "label": "Vignette",
    "panel": "film",
    "fxsec": "vig"
  },
  {
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"vig\"] input",
    "app": "#sl-vig",
    "label": "Amount",
    "panel": "film",
    "fxsec": "vig"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"] button.sw",
    "app": "#tg-borders",
    "label": "Border",
    "panel": "frame",
    "fxsec": "borders"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"] input",
    "app": "#sl-b1-t",
    "label": "Inner thickness",
    "panel": "frame",
    "fxsec": "borders"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"] input",
    "app": "#sl-b2-t",
    "label": "Outer thickness",
    "panel": "frame",
    "fxsec": "borders"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"] button.select-btn",
    "app": "#sel-film-frame",
    "label": "Style",
    "panel": "frame",
    "fxsec": "borders"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"] input.txt",
    "app": "#in-frame-edge",
    "label": "Edge text",
    "panel": "frame",
    "fxsec": "borders"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"canvas\"] button.sw",
    "app": "#tg-canvas",
    "label": "Canvas",
    "panel": "frame",
    "fxsec": "canvas"
  },
  {
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"canvas\"] input",
    "app": "#sl-canvas-z",
    "label": "Zoom",
    "panel": "frame",
    "fxsec": "canvas"
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.select-btn",
    "app": "#sel-exp-fmt",
    "label": "Format",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] input",
    "app": "#sl-exp-q",
    "label": "Quality",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.select-btn",
    "app": "#sel-exp-size",
    "label": "Resize (long edge)",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.select-btn",
    "app": "#sel-exp-sharp",
    "label": "Output sharpening",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.sw",
    "app": "#tg-exp-hdr",
    "label": "HDR (gain map)",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] input",
    "app": "#sl-exp-wm-op",
    "label": "Opacity",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.select-btn",
    "app": "#sel-exp-preset",
    "label": "Export preset",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.wide-btn.ghost.danger",
    "app": "#btn-exp-preset-del",
    "label": "",
    "panel": "export",
    "fxsec": null
  },
  {
    "wf": ".tp-panel[data-panel=\"export\"] button.wide-btn.primary",
    "app": "#btn-fx-export",
    "label": "",
    "panel": "export",
    "fxsec": null
  }
];

export const INVENTORY_ZONES = [
  {
    "label": "looks-panel",
    "wf": ".tp-panel[data-panel=\"looks\"]",
    "app": "[data-fxsec=\"looks\"]",
    "appSection": "looks",
    "wfPanel": "looks"
  },
  {
    "label": "adjust-panel",
    "wf": ".tp-panel[data-panel=\"adjust\"]",
    "app": "[data-fxsec=\"adjust\"]",
    "appSection": "adjust",
    "wfPanel": "adjust"
  },
  {
    "label": "crop-panel",
    "wf": ".tp-panel[data-panel=\"crop\"] .grp[data-fxsec=\"crop\"]",
    "app": "[data-fxsec=\"crop\"]",
    "appSection": "crop",
    "wfPanel": "crop"
  },
  {
    "label": "detail-panel",
    "wf": ".tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"nr\"],.tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"lens\"],.tp-panel[data-panel=\"detail\"] .grp[data-fxsec=\"deconv\"]",
    "app": "[data-fxsec=\"nr\"],[data-fxsec=\"lens\"],[data-fxsec=\"deconv\"]",
    "appSection": "detail",
    "wfPanel": "detail"
  },
  {
    "label": "color-panel",
    "wf": ".tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"curves\"],.tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"hsl\"],.tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"pointcolor\"],.tp-panel[data-panel=\"color\"] .grp[data-fxsec=\"wheels\"]",
    "app": "[data-fxsec=\"curves\"],[data-fxsec=\"hsl\"],[data-fxsec=\"pointcolor\"],[data-fxsec=\"wheels\"]",
    "appSection": "color",
    "wfPanel": "color"
  },
  {
    "label": "retouch-panel",
    "wf": ".tp-panel[data-panel=\"retouch\"]",
    "app": "[data-fxsec=\"retouch\"]",
    "appSection": "retouch",
    "wfPanel": "retouch"
  },
  {
    "label": "masks-panel",
    "wf": ".tp-panel[data-panel=\"masks\"]",
    "app": "[data-fxsec=\"local\"]",
    "appSection": "masks",
    "wfPanel": "masks"
  },
  {
    "label": "film-panel",
    "wf": ".tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"grain\"],.tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"hal\"],.tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"bloom\"],.tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"art\"],.tp-panel[data-panel=\"film\"] .grp[data-fxsec=\"vig\"]",
    "app": "[data-fxsec=\"grain\"],[data-fxsec=\"hal\"],[data-fxsec=\"bloom\"],[data-fxsec=\"art\"],[data-fxsec=\"vig\"]",
    "appSection": "film",
    "wfPanel": "film"
  },
  {
    "label": "frame-panel",
    "wf": ".tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"borders\"],.tp-panel[data-panel=\"frame\"] .grp[data-fxsec=\"canvas\"]",
    "app": "[data-fxsec=\"borders\"],[data-fxsec=\"canvas\"]",
    "appSection": "frame",
    "wfPanel": "frame"
  },
  {
    "label": "export-panel",
    "wf": ".tp-panel[data-panel=\"export\"]",
    "app": "[data-fxsec=\"export\"]",
    "appSection": "export",
    "wfPanel": "export"
  },
  {
    "label": "info-panel",
    "wf": ".tp-panel[data-panel=\"info\"]",
    "app": "[data-fxsec=\"info\"]",
    "appSection": "info",
    "wfPanel": "info"
  }
];
