import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
const ROOT='/Users/tareqameer/Documents/GitHub/Chroma-App';
const MIME={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.wasm':'application/wasm','.png':'image/png','.json':'application/json','.cube':'text/plain'};
const server=await new Promise(r=>{const s=createServer(async(rq,rs)=>{try{const p=path.join(ROOT,decodeURIComponent(rq.url.split('?')[0]));const d=await readFile(p);rs.setHeader('Cross-Origin-Opener-Policy','same-origin');rs.setHeader('Cross-Origin-Embedder-Policy','require-corp');rs.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});rs.end(d);}catch{rs.writeHead(404);rs.end();}});s.listen(0,'127.0.0.1',()=>r(s));});
const base=`http://127.0.0.1:${server.address().port}`;
const br=await chromium.launch({args:['--use-gl=swiftshader','--use-angle=swiftshader','--disable-gpu-sandbox','--enable-unsafe-swiftshader']});
const pg=await br.newPage({viewport:{width:1400,height:1000}});
pg.on('pageerror',e=>console.error('[pageerror]',e.message));
pg.on('console',m=>console.error('[console]',m.type(),m.text()));
await pg.goto(`${base}/chromasmith-22.html`,{waitUntil:'load'});
await pg.waitForFunction(()=>typeof window.loadFXImages==='function',null,{timeout:30000});
const fx=(await readFile(path.join(ROOT,'test/fixtures/portrait.png'))).toString('base64');
await pg.evaluate(async b64=>{const bin=atob(b64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);await window.loadFXImages([new File([a],'portrait.png',{type:'image/png'})]);},fx);
await pg.waitForFunction(()=>typeof fxImages!=='undefined'&&fxImages.length>0,null,{timeout:20000});
await pg.evaluate(()=>{const tg=document.getElementById('tg-hsl');if(tg&&!tg.classList.contains('on'))toggleFX('hsl');});
const res=await pg.evaluate(async()=>{
  const wait=()=>new Promise(r=>setTimeout(r,250));
  hslBand=hslBand||'r';
  fxState.hsl.sat[hslBand]=40; fxState.hsl.hue[hslBand]=20;
  bakeHsl(); hslSyncUI(); fxUpdate();
  await wait();
  const before=JSON.stringify(fxState.hsl);
  const card=document.querySelector('.fx-ctrl[data-fxsec="hsl"]');
  const allBtn=card.querySelector('.fx-ctrl-title-reset');
  const scopedBtn=card.querySelector('.fx-ctrl-title-reset-scoped');
  allBtn.click();
  await wait();
  const afterAll=JSON.stringify(fxState.hsl);
  return {before, afterAll, allFound:!!allBtn, scopedFound:!!scopedBtn};
});
console.log(JSON.stringify(res,null,1));
await br.close(); server.close();
