import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
const [root, imgdir] = process.argv.slice(2);
const srv = createServer(async (q,r)=>{try{const b=await readFile(path.join(root,decodeURIComponent(q.url.split('?')[0]).replace(/\/$/,'/index.html')));r.setHeader('content-type',q.url.endsWith('.html')?'text/html':'application/octet-stream');r.end(b)}catch{r.statusCode=404;r.end()}}).listen(0);
const port = srv.address().port;
const br = await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const pg = await br.newPage({viewport:{width:1200,height:800}});
pg.on('pageerror',e=>console.log('pageerror',e.message));
await pg.goto(`http://localhost:${port}/chromasmith-22.html`);
await pg.waitForTimeout(1500);
const files = Array.from({length:30},(_,i)=>`${imgdir}/p${String(i).padStart(2,'0')}.png`);
await pg.setInputFiles('#in-fx-img', files);
await pg.waitForFunction(()=>fxImages.length>=30,null,{timeout:60000});
await pg.waitForTimeout(1500);
const st = ()=>pg.evaluate(()=>{const el=document.getElementById('fx-filmstrip');const a=el.querySelector('.active');const er=el.getBoundingClientRect(),ar=a&&a.getBoundingClientRect();return {sl:Math.round(el.scrollLeft),max:el.scrollWidth-el.clientWidth,cur:fxCurIdx,vis:!!a&&ar.left>=er.left-1&&ar.right<=er.right+1}});
const sel = async(label,fn)=>{await pg.evaluate(()=>{document.getElementById('fx-filmstrip').scrollLeft=SLV});await pg.waitForTimeout(300);const b=await st();await fn();await pg.waitForTimeout(700);const a=await st();console.log(label.padEnd(14),'before',b.sl,'after',a.sl,'cur',a.cur,'activeVisible',a.vis,'max',a.max, b.sl===a.sl?'HELD':'JUMPED')};
await pg.evaluate(()=>{document.getElementById('fx-filmstrip').scrollLeft=SLV});
await sel('click thumb 3',()=>pg.evaluate(()=>document.querySelectorAll('.fs-thumb')[3].click()));
await sel('click thumb 4',()=>pg.evaluate(()=>document.querySelectorAll('.fs-thumb')[4].click()));
await pg.evaluate(()=>{document.body.focus()});
await sel('key ArrowRight',()=>pg.keyboard.press('ArrowRight'));
await sel('key ArrowLeft',()=>pg.keyboard.press('ArrowLeft'));
await sel('offscreen 25',()=>pg.evaluate(()=>document.querySelectorAll('.fs-thumb')[25].click()));
await br.close();srv.close();
