"""
Shared grain calibration module — geometry, measurement, and the numpy port of
the committed shader's grain math (chromasmith-22.html comp pass, ~line 739-749).

Geometry mirrors calib/grain_chart_geo.txt (generated by gen_grain_chart.py).
Measure noise STATISTICALLY (grain is stochastic — never pixel-diff): local
high-pass residual stddev per flat zone, per channel, per Dehancer amount.
This is the same "sample flat interiors, not edges" discipline that the
halation session learned the hard way.
"""
import numpy as np
from PIL import Image
from scipy.ndimage import uniform_filter

# ── chart geometry (must match gen_grain_chart.py constants) ─────────────────
HUES = ['R', 'G', 'B', 'C', 'M', 'Y', 'SkinLt', 'SkinMid', 'SkinDk',
        'Gray18', 'Cine25', 'Cine75']
LUMA_STEPS = [0.0, 0.10, 0.25, 0.40, 0.55, 0.70, 0.85, 1.00]
A_X0, A_Y0 = 120, 120
CELL_W, CELL_H, GAP = 520, 150, 8

PROF = [('Shadow10', (26, 26, 26)), ('Gray18', (118, 118, 118)),
        ('Gray50', (188, 188, 188)), ('SkinMid', (224, 172, 138)),
        ('PureR', (255, 0, 0)), ('PureG', (0, 255, 0)), ('PureB', (0, 0, 255))]
B_Y0, B_H = 2270, 230
BW = (4800 - 240) // len(PROF)

CHECKER = {'4px': (120, 1640), '16px': (1700, 3220), '64px': (3280, 4680)}
E_Y0, E_H = 3070, 280


def matrix_cell(row_name, luma):
    """Inset rect (x0,y0,x1,y1) for a Color x Luminance matrix cell."""
    ri = HUES.index(row_name)
    ci = LUMA_STEPS.index(luma)
    x0 = A_X0 + ci * CELL_W
    y0 = A_Y0 + ri * CELL_H
    m = 24  # inset further from GAP edge to avoid any residual edge contamination
    return (x0 + m, y0 + m, x0 + CELL_W - m, y0 + CELL_H - m)


def profile_block(name):
    i = [n for n, _ in PROF].index(name)
    x0 = 120 + i * BW
    return (x0 + 30, B_Y0 + 30, x0 + BW - 30, B_Y0 + B_H - 30)


def checker_block(size):
    x0, x1 = CHECKER[size]
    return (x0 + 20, E_Y0 + 20, x1 - 20, E_Y0 + E_H - 20)


# ── statistical measurement (high-pass residual std == "grain strength") ─────
def patch(img, rect):
    x0, y0, x1, y1 = rect
    return img[y0:y1, x0:x1].astype(np.float32)


def noise_std(img, rect, blur=9):
    """Per-channel stddev of (patch - locally_smoothed(patch)).
    On a flat region this isolates the grain/noise component from the signal —
    exactly the 'measure flat interiors' approach validated for halation."""
    p = patch(img, rect)
    smooth = uniform_filter(p, size=(blur, blur, 1))
    resid = p - smooth
    return resid.reshape(-1, 3).std(axis=0)  # [sigR, sigG, sigB]


def autocorr_halfwidth(img, rect, blur=9, max_lag=40):
    """Radial half-width of the residual's autocorrelation -> a 'grain size'
    proxy (bigger halfwidth = coarser/clumpier grain)."""
    p = patch(img, rect).mean(axis=2)
    smooth = uniform_filter(p, size=blur)
    resid = p - smooth
    resid -= resid.mean()
    f = np.fft.rfft2(resid)
    ac = np.fft.irfft2(f * np.conj(f), s=resid.shape)
    ac = np.fft.fftshift(ac, axes=0)
    cy, cx = ac.shape[0] // 2, 0
    prof = ac[cy, cx:cx + max_lag]
    prof = prof / prof[0]
    below = np.where(prof < 0.5)[0]
    return float(below[0]) if len(below) else float(max_lag)


def load(path):
    return np.array(Image.open(path).convert('RGB'))


# ── v2: per-channel signal-dependent ("shot-noise-like") grain model ─────────
# measure_grain.py found Dehancer's grain scales with EACH channel's own
# exposure (sigma_B >> sigma_R,G on blue patches and vice-versa for red) —
# the fixed-ratio luma-masked v1 (rm*0.88/0.72) cannot reproduce that. The
# sigma/sqrt(value) check is roughly constant per channel (shot-noise:
# variance ∝ signal, std ∝ sqrt(signal)) modulo a per-channel sensitivity
# weight (kR,kG,kB) and highlight clipping (handled naturally by np.clip).
#   sigma_c ≈ k_c * amount_norm^powA * value_c^powG          (powG≈0.5)
# GLSL-portable: pure pow()/clip, same h21 hash, independent per-channel noise.
def synth_patch(rgb01, size=96):
    return np.tile(np.array(rgb01, dtype=np.float32), (size, size, 1))


def apply_grain_v2(res, amount_norm, params, seed=0.0):
    kR, kG_, kB, powG, powA, grSz = (params['kR'], params['kG'], params['kB'],
                                     params['powG'], params['powA'], params['grSz'])
    H, W = res.shape[:2]
    yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
    uv = np.stack([xx / W, yy / H], axis=-1)
    gc = uv / max(grSz, 1e-4) + seed
    nr = h21_np(gc + np.array([.07, .43])) - 0.5
    ng = h21_np(gc + np.array([.51, .19])) - 0.5
    nb = h21_np(gc + np.array([.83, .67])) - 0.5
    v = np.clip(res, 0., 1.)
    aScale = amount_norm ** powA if amount_norm > 0 else 0.0
    sR = kR * aScale * v[..., 0] ** powG
    sG = kG_ * aScale * v[..., 1] ** powG
    sB = kB * aScale * v[..., 2] ** powG
    noise = np.stack([nr * sR, ng * sG, nb * sB], axis=-1)
    return np.clip(res + noise, 0., 1.)


def predict_sigma_v2(value01, amount_norm, params):
    """Analytic sigma prediction (no clipping) for the fast optimizer loop —
    UNIT_NOISE_STD = std of (h21()-0.5), a uniform var on [-.5,.5) = 1/sqrt(12)."""
    UNIT = 1.0 / np.sqrt(12.0)
    k = np.array([params['kR'], params['kG'], params['kB']])
    return k * (amount_norm ** params['powA']) * (np.asarray(value01) ** params['powG']) * UNIT * 255.0


# ── v3: two-component grain — shared luminance-correlated base + per-channel
# self-signal term (mirrors the halation model's "two emission drivers" insight,
# discovered the same way: v2's pure-per-channel model couldn't reproduce
# Dehancer's nonzero grain on a hue's OFF channels — e.g. pure-red still grains
# its G/B somewhat — proving a shared/luminance-correlated component exists
# alongside the per-channel shot-noise-like term).
#   base_c   = lum ^ powL                       (shared: correlates all channels)
#   self_c   = clamp(value_c,0,1) ^ powG         (per-channel signal-dependent)
#   sigma_c  = k_c * amount_norm^powA * (wL*base_c + (1-wL)*self_c)
LUMA_W = np.array([.2126, .7152, .0722])
UNIT_STD = 1.0 / np.sqrt(12.0)


def apply_grain_v3(res, amount_norm, params, seed=0.0):
    kR, kG_, kB, powG, powL, powA, wL, grSz = (
        params['kR'], params['kG'], params['kB'], params['powG'],
        params['powL'], params['powA'], params['wL'], params['grSz'])
    H, W = res.shape[:2]
    yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
    uv = np.stack([xx / W, yy / H], axis=-1)
    gc = uv / max(grSz, 1e-4) + seed
    nr = h21_np(gc + np.array([.07, .43])) - 0.5
    ng = h21_np(gc + np.array([.51, .19])) - 0.5
    nb = h21_np(gc + np.array([.83, .67])) - 0.5
    v = np.clip(res, 0., 1.)
    lum = v @ LUMA_W
    base = lum ** powL
    aScale = amount_norm ** powA if amount_norm > 0 else 0.0
    k = np.array([kR, kG_, kB])
    selfv = v ** powG
    strength = k * (wL * base[..., None] + (1 - wL) * selfv)
    sigma = strength * aScale
    noise = np.stack([nr, ng, nb], axis=-1) * sigma
    return np.clip(res + noise, 0., 1.)


def predict_sigma_v3(value01, amount_norm, params):
    value01 = np.asarray(value01, dtype=np.float64)
    lum = float(value01 @ LUMA_W)
    base = lum ** params['powL']
    selfv = value01 ** params['powG']
    k = np.array([params['kR'], params['kG'], params['kB']])
    strength = k * (params['wL'] * base + (1 - params['wL']) * selfv)
    return strength * (amount_norm ** params['powA']) * UNIT_STD * 255.0


# ── v4: v3 + per-channel HIGHLIGHT-ROLLOFF gate ──────────────────────────────
# measure_grain.py shows fully-saturated/clipped channels (e.g. pure-red R≈1.0
# at full luma) carry ~zero Dehancer grain, while v3 (no gate) keeps predicting
# substantial sigma there because clip(res+noise) still has measurable spread
# below the ceiling. Dehancer's film response must compress/clip BEFORE grain
# is added in those zones — so gate each channel's strength by how close its
# own value is to full saturation:
#   gate_c = 1 - smoothstep(hiLo, hiHi, value_c)
# Gray50 (v≈0.74) must stay ~ungated (hiLo>0.74), pure-channel-at-full (v=1.0)
# must be ~fully gated (hiHi<=1.0) — i.e. the rolloff is a narrow, steep
# highlight-only window, not a broad symmetric falloff.
def _smoothstep(lo, hi, x):
    t = np.clip((x - lo) / max(hi - lo, 1e-6), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def apply_grain_v4(res, amount_norm, params, seed=0.0):
    kR, kG_, kB, powG, powL, powA, wL, grSz, hiLo, hiHi = (
        params['kR'], params['kG'], params['kB'], params['powG'],
        params['powL'], params['powA'], params['wL'], params['grSz'],
        params['hiLo'], params['hiHi'])
    H, W = res.shape[:2]
    yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
    uv = np.stack([xx / W, yy / H], axis=-1)
    gc = uv / max(grSz, 1e-4) + seed
    nr = h21_np(gc + np.array([.07, .43])) - 0.5
    ng = h21_np(gc + np.array([.51, .19])) - 0.5
    nb = h21_np(gc + np.array([.83, .67])) - 0.5
    v = np.clip(res, 0., 1.)
    lum = v @ LUMA_W
    base = lum ** powL
    aScale = amount_norm ** powA if amount_norm > 0 else 0.0
    k = np.array([kR, kG_, kB])
    selfv = v ** powG
    gate = 1.0 - _smoothstep(hiLo, hiHi, v)
    strength = k * (wL * base[..., None] + (1 - wL) * selfv) * gate
    sigma = strength * aScale
    noise = np.stack([nr, ng, nb], axis=-1) * sigma
    return np.clip(res + noise, 0., 1.)


def predict_sigma_v4(value01, amount_norm, params):
    value01 = np.asarray(value01, dtype=np.float64)
    lum = float(value01 @ LUMA_W)
    base = lum ** params['powL']
    selfv = value01 ** params['powG']
    k = np.array([params['kR'], params['kG'], params['kB']])
    gate = 1.0 - _smoothstep(params['hiLo'], params['hiHi'], value01)
    strength = k * (params['wL'] * base + (1 - params['wL']) * selfv) * gate
    return strength * (amount_norm ** params['powA']) * UNIT_STD * 255.0


# ── numpy port of the committed shader grain (lines 739-749) ─────────────────
def h21_np(p):
    p = np.mod(p * np.array([127.1, 311.7]), 1.0)
    p = p + np.sum(p * (p + 45.32), axis=-1, keepdims=True)
    return np.mod(p[..., 0] * p[..., 1], 1.0)


def apply_grain(res, amount, size, gtype, seed=0.0, w=None, h=None):
    """res: float32 HxWx3 in [0,1] display-space. Mirrors GLSL lines 739-749."""
    H, W = res.shape[:2]
    yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
    uv = np.stack([xx / W, yy / H], axis=-1)
    grSz = max(size, 1e-4)
    gc = uv / grSz + seed
    g = h21_np(gc) - 0.5
    rm = gtype * 0.20
    gr = g + (h21_np(gc + np.array([.13, .29])) - 0.5) * rm
    gg = g + (h21_np(gc + np.array([.47, .71])) - 0.5) * rm * 0.88
    gb = g + (h21_np(gc + np.array([.83, .19])) - 0.5) * rm * 0.72
    if gtype > 0.5:
        cl = (h21_np(gc * 0.18 + 0.5) - 0.5) * 0.55
        cl2 = (h21_np(gc * 0.06 + 0.3) - 0.5) * 0.25
        gr = gr + cl + cl2
        gg = gg + cl * 0.65 + cl2
        gb = gb + cl * 0.5 + cl2 * 1.8
    lu = res @ np.array([.2126, .7152, .0722])
    sf = 0.04 if gtype > 0.5 else 0.0
    msk = np.clip(4. * lu * (1. - lu) * 0.95 + sf, 0., 1.)
    noise = np.stack([gr, gg, gb], axis=-1) * amount * 0.24 * msk[..., None]
    return np.clip(res + noise, 0., 1.)
