#!/usr/bin/env python3
"""Cube (.cube 3D LUT) I/O + regularized inverse, for fujify STD<->VLOG composition.

A .cube stores N^3 RGB triples with RED changing fastest:
    for b: for g: for r: <value>
We expose LUTs as arrays indexed lut[r, g, b, :] in [0,1] input/output space.
"""
import sys
import numpy as np


def read_cube(path):
    size = None
    dmin = np.zeros(3)
    dmax = np.ones(3)
    title = ""
    comment = ""
    vals = []
    with open(path, "r") as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            if s.startswith("#"):
                comment = s[1:].strip()
                continue
            up = s.upper()
            if up.startswith("TITLE"):
                title = s.split(None, 1)[1].strip().strip('"') if len(s.split(None, 1)) > 1 else ""
                continue
            if up.startswith("LUT_3D_SIZE"):
                size = int(s.split()[1]); continue
            if up.startswith("LUT_1D_SIZE"):
                raise ValueError("1D LUT not supported: " + path)
            if up.startswith("DOMAIN_MIN"):
                dmin = np.array([float(x) for x in s.split()[1:4]]); continue
            if up.startswith("DOMAIN_MAX"):
                dmax = np.array([float(x) for x in s.split()[1:4]]); continue
            parts = s.split()
            if len(parts) == 3:
                try:
                    vals.append([float(parts[0]), float(parts[1]), float(parts[2])])
                except ValueError:
                    pass
    if size is None:
        raise ValueError("no LUT_3D_SIZE in " + path)
    vals = np.asarray(vals, dtype=np.float64)
    if vals.shape[0] != size ** 3:
        raise ValueError(f"{path}: expected {size**3} entries, got {vals.shape[0]}")
    # flat index i = r + N*g + N*N*b  ->  reshape (b,g,r,3) then transpose to (r,g,b,3)
    arr = vals.reshape(size, size, size, 3)          # [b, g, r, c]
    lut = np.transpose(arr, (2, 1, 0, 3)).copy()      # [r, g, b, c]
    return {"size": size, "lut": lut, "domain_min": dmin, "domain_max": dmax,
            "title": title, "comment": comment}


def write_cube(path, lut, title="Generated by chromasmith fujify", comment=None):
    size = lut.shape[0]
    arr = np.transpose(lut, (2, 1, 0, 3))             # back to [b, g, r, c]
    flat = arr.reshape(-1, 3)
    with open(path, "w") as f:
        f.write(f'TITLE "{title}"\n')
        if comment:
            f.write(f"#{comment}\n")
        f.write(f"LUT_3D_SIZE {size}\n\n")
        for r in flat:
            f.write(f"{r[0]:.6f} {r[1]:.6f} {r[2]:.6f}\n")


def lattice(size):
    """Regular input grid, shape (size,size,size,3), coords[r,g,b] = (r,g,b)/(size-1)."""
    a = np.linspace(0.0, 1.0, size)
    R, G, B = np.meshgrid(a, a, a, indexing="ij")
    return np.stack([R, G, B], axis=-1)


def apply_lut(lut, rgb):
    """Trilinear interpolation. rgb: (...,3) in [0,1]. Returns same shape."""
    size = lut.shape[0]
    shp = rgb.shape
    pts = np.clip(rgb.reshape(-1, 3), 0.0, 1.0) * (size - 1)
    i0 = np.floor(pts).astype(np.int64)
    i0 = np.clip(i0, 0, size - 2)
    f = pts - i0
    out = np.zeros((pts.shape[0], 3))
    for dr in (0, 1):
        for dg in (0, 1):
            for db in (0, 1):
                w = (f[:, 0] if dr else 1 - f[:, 0]) * \
                    (f[:, 1] if dg else 1 - f[:, 1]) * \
                    (f[:, 2] if db else 1 - f[:, 2])
                out += w[:, None] * lut[i0[:, 0] + dr, i0[:, 1] + dg, i0[:, 2] + db]
    return out.reshape(shp)


def invert_at(lut, queries, neighbors=80, smoothing=1e-4):
    """Inverse LUT: for each query output color, find the input that produces it.
    Fits a scattered map (forward-output -> forward-input) and evaluates at `queries`.
    queries: (...,3). Returns inputs (...,3), clipped to [0,1]."""
    from scipy.interpolate import RBFInterpolator
    size = lut.shape[0]
    src = lut.reshape(-1, 3)              # forward outputs
    dst = lattice(size).reshape(-1, 3)    # forward inputs
    shp = queries.shape
    q = queries.reshape(-1, 3)
    rbf = RBFInterpolator(src, dst, neighbors=neighbors, kernel="linear",
                          smoothing=smoothing)
    inv = rbf(q)
    return np.clip(inv, 0.0, 1.0).reshape(shp)


def delta_e_approx(a, b):
    """Cheap perceptual-ish error: scaled Euclidean in sRGB*255 (proxy for dE).
    Returns per-sample distance for arrays (...,3) in [0,1]."""
    d = (a - b) * 255.0
    return np.sqrt(np.sum(d * d, axis=-1))


def _selftest():
    import glob, os
    here = os.path.dirname(__file__)
    cands = sorted(glob.glob(os.path.join(here, "vlog_cubes", "*.cube")))
    assert cands, "no vlog cubes found; run download step first"
    c = read_cube(cands[0])
    print(f"read {os.path.basename(cands[0])}: size={c['size']} comment='{c['comment']}'")
    lut = c["lut"]
    # apply_lut on lattice reproduces the stored LUT exactly
    lat = lattice(c["size"])
    re = apply_lut(lut, lat)
    err = np.abs(re - lut).max()
    print(f"apply_lut@lattice max|err| = {err:.2e}  (should be ~0)")
    assert err < 1e-9
    # invert round-trip: invert_at(forward outputs) should recover lattice inputs
    sub = lat[::8, ::8, ::8]                       # subsample for speed
    fwd = apply_lut(lut, sub)
    inv = invert_at(lut, fwd)
    de = delta_e_approx(inv, sub)
    # report on non-clipped region (where forward output isn't saturated)
    nonclip = (fwd > 0.01).all(-1) & (fwd < 0.99).all(-1)
    print(f"invert round-trip dE (input space, all):     mean={de.mean():.3f} p95={np.percentile(de,95):.3f}")
    if nonclip.any():
        print(f"invert round-trip dE (non-clipped region):   mean={de[nonclip].mean():.3f} p95={np.percentile(de[nonclip],95):.3f}")
    print("cube_io selftest OK")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        _selftest()
    else:
        print("usage: cube_io.py --selftest")
